### PR TITLE
fix: remove .all-contributorsrc from .prettierignore

### LINKED ISSUE #801: 🛠 Tooling: Remove .all-contributorsrc from .prettierignore
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/create-typescript-app/issues?q=is%3Aissue) and found none that matched my issue.

### Overview

https://github.com/JoshuaKGoldberg/create-typescript-app/blob/cdcf22b9344591c8b3803904a91a87082b372e1b/.prettierignore#L5-L6

https://github.com/all-contributors/cli/issues/347 is now resolved. So we should be able to remove these two lines from `.prettierignore`. Yay!

### Additional Info

Note that the template for `.prettierignore` will also need to be updated:

https://github.com/JoshuaKGoldberg/create-typescript-app/blob/f4f0233813092320c1a796eb88a97e529647071b/src/steps/writing/creation/rootFiles.ts#L50-L57

### PR DESCRIPTION
**Pull request by conrmahr**
## PR Checklist

- [x] Addresses an existing open issue: fixes #801
- [x] That issue was marked as [`status: accepting prs`](https://github.com/JoshuaKGoldberg/create-typescript-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22status%3A+accepting+prs%22)
- [x] Steps in [CONTRIBUTING.md](https://github.com/JoshuaKGoldberg/create-typescript-app/blob/main/.github/CONTRIBUTING.md) were taken

## Overview

This PR is a fix for the all-contributors/cli#347 issue now being resolved. Ignoring the `.all-contributorsrc` file in the `.prettierignore` file is unnecessary. 😎

### CODE REVIEW

**Review by JoshuaKGoldberg — APPROVED** [review]
💯 perfect, thanks!

**Review by JoshuaKGoldberg — CHANGES_REQUESTED** [review]
Oop, looks like there's a formatting error - can you fix it @conrmahr?

**Comment by conrmahr** [comment]
✅ `pnpm format --list-different` - Doesn't error out now locally.
✅ `pnpn test` - All tests passed.

Hope that fixes it. 🙏

**Review by JoshuaKGoldberg — APPROVED** [review]
Thanks!

**Comment by JoshuaKGoldberg** [comment]
@all-contributors please add @conrmahr for code.

> 🤖 Beep boop! This comment was added automatically by [all-contributors-auto-action](https://github.com/marketplace/actions/all-contributors-auto-action).
> Not all contributions can be detected from Git & GitHub alone. Please comment any missing contribution types this bot missed.
> ...and of course, thank you for contributing! 💙

**Pull request merged**
