### PR TITLE
feat: speculative more informative error message

### LINKED ISSUE #1616: 🐛 Bug: `gh: command not found` when running `npx create-typescript-app --base prompt --mode create`
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/create-typescript-app/issues?q=is%3Aissue) and found none that matched my issue.

### Expected

I ran `npx create-typescript-app --base prompt --mode create` and experienced a `gh: command not found` error

### Actual

```
┌  ✨ Welcome to create-typescript-app 1.67.5! ✨
│
│  ⚠️ This template is early stage, opinionated, and not endorsed by the TypeScript team. ⚠️
│  ⚠️ If any tooling it sets displeases you, you can always remove that portion manually. ⚠️
│
◇  What organization or user will the repository be under?
│  johnnyreilly
│
◇  What will the kebab-case name of the repository be?
│  test-create-repo
│
◇  ❌ Error checking GitHub authentication.
file:///Users/john.reilly/.npm/_npx/4aa729db9999bfc4/node_modules/create-typescript-app/lib/shared/cli/spinners.js:16
    throw new Error(`Failed ${lowerFirst(label)}`, { cause: error });
          ^

Error: Failed checking GitHub authentication
    at withSpinner (file:///Users/john.reilly/.npm/_npx/xx/node_modules/create-typescript-app/lib/shared/cli/spinners.js:16:11)
    at async readOptions (file:///Users/john.reilly/.npm/_npx/xx/node_modules/create-typescript-app/lib/shared/options/readOptions.js:119:38)
    at async Object.create (file:///Users/john.reilly/.npm/_npx/xx/node_modules/create-typescript-app/lib/create/index.js:12:18)
    at async bin (file:///Users/john.reilly/.npm/_npx/xx/node_modules/create-typescript-app/lib/bin/index.js:67:36)
    at async file:///Users/john.reilly/.npm/_npx/xx/node_modules/create-typescript-app/bin/index.js:4:20 {
  [cause]: Error: Command failed: gh auth token
  /bin/sh: gh: command not found
  
      at genericNodeError (node:internal/errors:984:15)
      at wrappedFn (node:internal/errors:538:14)
      at ChildProcess.exithandler (node:child_process:422:12)
      at ChildProcess.emit (node:events:519:28)
      at maybeClose (node:internal/child_process:1105:16)
      at Socket.<anonymous> (node:internal/child_process:457:11)
      at Socket.emit (node:events:519:28)
      at Pipe.<anonymous> (node:net:338:12) {
    code: 127,
    killed: false,
    signal: null,
    cmd: 'gh auth token',
    stdout: '',
    stderr: '/bin/sh: gh: command not found\n'
  }
}
```

### Additional Info

I tried first to create a repository for my organisation.  That failed.  I thought "ah, this is an organisation issue probably" so I retested creating under my username of `johnnyreilly` and that failed in the same way.  So I think it's a general issue.

### PR DESCRIPTION
**Pull request by johnnyreilly**
## PR Checklist

- [x] Addresses an existing open issue: fixes #1616
- [x] That issue was marked as [`status: accepting prs`](https://github.com/JoshuaKGoldberg/create-typescript-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22status%3A+accepting+prs%22)
- [ ] Steps in [CONTRIBUTING.md](https://github.com/JoshuaKGoldberg/create-typescript-app/blob/main/.github/CONTRIBUTING.md) were taken

## Overview

This is not ready to merge - it's just an idea of how a particular error could be made more actionable.   It may not be desired - particularly given https://github.com/JoshuaKGoldberg/create-typescript-app/pull/1000

If it is desired I can make it cleaner than this.

### CODE REVIEW

**Review by JoshuaKGoldberg — CHANGES_REQUESTED** [review]
Yeah this is lovely! If you can get the tests passing I'd say it's ready for merge. LMK if you want help, I know the migration ones can be annoying. 😅

**Comment by johnnyreilly** [comment]
Awesome - will probably take a look tomorrow!

**Comment by JoshuaKGoldberg** [comment]
👋 ping @johnnyreilly, is this still on your radar?

**Comment by johnnyreilly** [comment]
I had forgotten this existed! Sorry. Might take a look when things quiet down, but can't guarantee. Feel free to proceed without me

**Comment by JoshuaKGoldberg** [comment]
Ah, yeah, it ended up having roughly the same error message experience from #1000. Great!

**Pull request closed without merging**
