### PR TITLE
docs: fix indentations in README

### LINKED ISSUE #1041: 🛠 Tooling: Lack of indentation in generated README.md all-contributors badge
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/create-typescript-app/issues?q=is%3Aissue) and found none that matched my issue.

### Overview

When you first `--mode create` a repository using `create-typescript-app` right now, if `--base everything` is specified, this is what the badges in the README.md roughly look like:

```md
<p align="center">
	<!-- prettier-ignore-start -->
	<!-- ALL-CONTRIBUTORS-BADGE:START - Do not remove or modify this section -->
<a href="#contributors" target="_blank"><img alt="All Contributors: 1 👪" src="https://img.shields.io/badge/all_contributors-1_👪-21bb42.svg" /></a>
<!-- ALL-CONTRIBUTORS-BADGE:END -->
	<!-- prettier-ignore-end -->
	<a href="https://codecov.io/gh/asdf/asdf" target="_blank"><img alt="Codecov Test Coverage" src="https://codecov.io/gh/asdf/asdf/branch/main/graph/badge.svg"/></a>
	<a href="https://github.com/asdf/asdf/blob/main/.github/CODE_OF_CONDUCT.md" target="_blank"><img alt="Contributor Covenant" src="https://img.shields.io/badge/code_of_conduct-enforced-21bb42" /></a>
	<a href="https://github.com/asdf/asdf/blob/main/LICENSE.md" target="_blank"><img alt="License: MIT" src="https://img.shields.io/github/license/asdf/asdf?color=21bb42"></a>
	<img alt="Style: Prettier" src="https://img.shields.io/badge/style-prettier-21bb42.svg" />
	<img alt="TypeScript: Strict" src="https://img.shields.io/badge/typescript-strict-21bb42.svg" />
	<img alt="npm package version" src="https://img.shields.io/npm/v/create-typescript-app?color=21bb42" />
</p>
```

The indentation situation was made better in #1038, but not completely perfect. Note the lack of indentation in the all-contributors `<a ...` and `<!-- ALL-CONTRIBUTORS-BADGE:END -->` lines. It would be nice if those two lines could be indented consistently with the rest of them...
1. `<a ...`: probably a matter of updating the `.all-contributorsrc` badge template?
2. `<!-- ALL-CONTRIBUTORS-BADGE:END -->`: I don't know and haven't looked into it much. Maybe a bug / feature request to file on allcontributors in some way? Maybe?

This is pretty low priority as it doesn't actually impact users. But if anybody is motivated and wants to take a look, I'd love to get this ironed out. 😄 

### Additional Info

Quick shell script I'm using to create a repo within the `create-typescript-app` project:

```plaintext
mkdir temp
cd temp
node ../bin/index.js --base everything --mode create --skip-github-api --title asdf --owner asdf --repository asdf --description asdf
```

### PR DESCRIPTION
**Pull request by jaas666**
## PR Checklist

- [X] Addresses an existing open issue: fixes #1041 
- [X] That issue was marked as [`status: accepting prs`](https://github.com/JoshuaKGoldberg/create-typescript-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22status%3A+accepting+prs%22)
- [X] Steps in [CONTRIBUTING.md](https://github.com/JoshuaKGoldberg/create-typescript-app/blob/main/.github/CONTRIBUTING.md) were taken

## Overview

Fixes the indentation for the `href` in README.md 🤘

### CODE REVIEW

**Comment by jaas666** [comment]
The `migration script` is failing but as far as I can tell it is successfully completing.

It looks like it's being marked failed so to a Warning:

```
(node:2028) ExperimentalWarning: Import assertions are not a stable feature of the JavaScript language. Avoid relying on their current behavior and syntax as those might change in a future version of Node.js.
(Use `node --trace-warnings ...` to show where the warning was created)
(node:2028) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
```

Maybe getting the warning now due to one of the recent package bumps?

**Comment by JoshuaKGoldberg** [comment]
Blurgh, yeah, #877. Fixed with be6b9929.

**Review by JoshuaKGoldberg — APPROVED** [review]
Yeah this works for now, thanks!

I played around with this a bit locally and couldn't find any way to get the auto-generated (`npx all-contributors-cli generate`) `<!-- ALL-CONTRIBUTORS-BADGE:END -->` to be indented too. Ah well.

**Comment by JoshuaKGoldberg** [comment]
@all-contributors please add @jaas666 for doc.

> 🤖 Beep boop! This comment was added automatically by [all-contributors-auto-action](https://github.com/marketplace/actions/all-contributors-auto-action).
> Not all contributions can be detected from Git & GitHub alone. Please comment any missing contribution types this bot missed.
> ...and of course, thank you for contributing! 💙

**Pull request merged**
