### PR TITLE
chore: cleanup --report-unused-disable-directives

### LINKED ISSUE #1089: 🛠 Tooling: Unnecessary --report-unused-disable-directives in templating
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/create-typescript-app/issues?q=is%3Aissue) and found none that matched my issue.

### Overview

Thanks to #1048, we see now that this repository has two bits of tooling that are different between its 🍎 actual files and 🍌 code templates (see _Additional Info_ below for explanation of the emojis):

* 🍎 Actual files: Does not use ESLint's `--report-unused-disable-directives`: https://github.com/JoshuaKGoldberg/create-typescript-app/blob/d66379b285b542a14d87c4f53cd0f0ccbc5310e9/package.json#L28
* 🍌 Code templates: Does have `--report-unused-disable-directives`: https://github.com/JoshuaKGoldberg/create-typescript-app/blob/d66379b285b542a14d87c4f53cd0f0ccbc5310e9/src/steps/writing/creation/writePackageJson.ts#L81

There's no need for adding `--report-unused-disable-directives` in the `lint` script, because it's now used in the ESLint config file: https://github.com/JoshuaKGoldberg/create-typescript-app/blob/d66379b285b542a14d87c4f53cd0f0ccbc5310e9/.eslintrc.cjs#L149C1-L149C1

Let's remove any and all references to `--report-unused-disable-directives` from this repo. Accepting PRs!

### Additional Info

This repository is two things:

* 🍎 An example of a working TypeScript repository, including builds, [Knip](https://knip.dev), package publishing, and more tooling
* 🍌 Code that can set up a new or existing repository using all of that repository tooling

For the most part, the [repository's end-to-end test for `--mode migration`](https://github.com/JoshuaKGoldberg/create-typescript-app/blob/main/.github/DEVELOPMENT.md#the-migration-script) makes sure that the 🍎 actual files and 🍌 code templates stay the same. As in, if one changes, the other needs to have the same change as well. But per #546, there are some files that were missed in that test. We're only now able to verify that they're the same as of #1048. That PR is where this discrepancy was discovered.

### PR DESCRIPTION
**Pull request by jaas666**
## PR Checklist

- [x] Addresses an existing open issue: fixes #1089 
- [x] That issue was marked as [`status: accepting prs`](https://github.com/JoshuaKGoldberg/create-typescript-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22status%3A+accepting+prs%22)
- [x] Steps in [CONTRIBUTING.md](https://github.com/JoshuaKGoldberg/create-typescript-app/blob/main/.github/CONTRIBUTING.md) were taken

## Overview

Removes all references to `--report-unused-disable-directives`

### CODE REVIEW

**Comment by jaas666** [comment]
Created this one as draft. I was getting some errors when running `pnpm run test`. My guess is that the snapshots need to be updated, probably related to the changes going on in #1048 

I'd wait for that one to be merged so CI tests run successfully on this one.

**Comment by JoshuaKGoldberg** [comment]
> getting some errors when running `pnpm run test`

Huh, weird, CI is passing here. I don't think you should need to wait for any other PR. What are the errors? The changes here look perfect to me. :smile:

**Comment by jaas666** [comment]
Ok let's try it

**Review by JoshuaKGoldberg — APPROVED** [review]
Video of a large boat crashing in waves onto a dock. Caption: 'ship it'

**Pull request merged**
