### PR TITLE
feat: simplified the titles of issue templates

### LINKED ISSUE #707: 🚀 Feature: Simplify the titles of issue templates
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/template-typescript-node-package/issues?q=is%3Aissue) and found none that matched my issue.

### Overview

Right now, the issue templates are:

* 🐛 Report a Bug
* 📝 Documentation
* 🚀 Request a Feature
* 🛠 Tooling

I think the ones that have 3 words can be simplified down to just one:

* 🐛 Bug
* 🚀 Feature

Less visual clutter. Easier to read. Good.

### Additional Info

Those titles are stored in `.yml` files in `.github/ISSUE_TEMPLATE`:

* https://github.com/JoshuaKGoldberg/template-typescript-node-package/blob/1c76c73c26828b29c40df01ad7f3af024bf42307/.github/ISSUE_TEMPLATE/01-bug.yml
* https://github.com/JoshuaKGoldberg/template-typescript-node-package/blob/1c76c73c26828b29c40df01ad7f3af024bf42307/.github/ISSUE_TEMPLATE/03-feature.yml

You'll also want to update the templates this repository uses when creating a new repo: https://github.com/JoshuaKGoldberg/template-typescript-node-package/blob/a386c870f5bc53ce3b30a8d31108c5726487ba78/src/steps/writing/creation/dotGitHub/issueTemplate.ts

### PR DESCRIPTION
**Pull request by RuthwikReddy09**
## PR Checklist

- [x] Addresses an existing open issue: fixes #707 
- [x] That issue was marked as [`status: accepting prs`](https://github.com/JoshuaKGoldberg/create-typescript-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22status%3A+accepting+prs%22)
- [x] Steps in [CONTRIBUTING.md](https://github.com/JoshuaKGoldberg/create-typescript-app/blob/main/.github/CONTRIBUTING.md) were taken

## Overview

simplified the titles of issue templates.
changed "Report a Bug" to "Bug" and "Request a Feature" to "Feature"

### CODE REVIEW

**Comment by JoshuaKGoldberg** [comment]
@RuthwikReddy09 can I ask why you're deleting branches after sending PRs? 🙂

**Comment by RuthwikReddy09** [comment]
@JoshuaKGoldberg I'm sorry. Some checks did not pass. So I did the whole thing again.

**Comment by JoshuaKGoldberg** [comment]
Nothing to be sorry about! You don't need to delete the branch/PR to get checks to run again. You can push commits to the same branch. See https://github.com/JoshuaKGoldberg/create-typescript-app/pull/727 - I do this all the time, with very sloppily written commit names.

https://docs.github.com/en/get-started/using-git/pushing-commits-to-a-remote-repository might be helpful if you haven't read it yet.

**Comment by RuthwikReddy09** [comment]
Ok Thanks 👍

**Pull request closed without merging**
