### PR TITLE
feat: move `--report-unused-disable-directives` cli option to `.eslintrc.cjs`

### PR DESCRIPTION
**Pull request by ryota-murakami**
## PR Checklist

- [x] Steps in [CONTRIBUTING.md](https://github.com/JoshuaKGoldberg/create-typescript-app/blob/main/.github/CONTRIBUTING.md) were taken

## Overview
I don't know this is intended, but generally forks include me preferred set in config file rather than cli options.

thanks take a look the PR!

### CODE REVIEW

**Review by JoshuaKGoldberg — APPROVED** [review]
💯 awesome! I'd missed that this was added to the config file options. Thanks for sending it in!

Just a few CI failures on the PR:
* Compliance: _"This PR's title should conform to specification at https://conventionalcommits.org/"_.
  * The bot should have posted this in the PR. Filed #732 on myself to see why it's not
* `.eslintrc.cjs` should be in sorted order

I'll just apply these now since they're not really related to the functional changes you made. Just a heads up 🙂

**Comment by JoshuaKGoldberg** [comment]
OH and `createESLintRC.ts` needs to include these changes. I'll send that up too.

**Comment by JoshuaKGoldberg** [comment]
@all-contributors please add @ryota-murakami for code.

> 🤖 Beep boop! This comment was added automatically by [all-contributors-auto-action](https://github.com/marketplace/actions/all-contributors-auto-action).
> Not all contributions can be detected from Git & GitHub alone. Please comment any missing contribution types this bot missed.
> ...and of course, thank you for contributing! 💙

**Comment by ryota-murakami** [comment]
@JoshuaKGoldberg Thank you for confirm the PR!
I'm using this template with own customize(swap to https://github.com/laststance/eslint-config-ts-prefixer etc) although there are a lot of points which should I learn.

Especially create new app and migrate existing projects CLI script are great resource for me!

👋

**Pull request merged**
