### PR TITLE
feat: add -v flag to display version

### LINKED ISSUE #704: 🚀 Feature: Add a --version CLI option
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/template-typescript-node-package/issues?q=is%3Aissue) and found none that matched my issue.

### Overview

Now that `npx template-typescript-node-package` is a supported -even recommended- use case, folks will want to be able to run `npx template-typescript-node-package --version`. Let's have it print out the package version.

Vaguely:

```shell
npx template-typescript-node-package --version
1.2.3
```

### Additional Info

Arguments are first parsed here: https://github.com/JoshuaKGoldberg/template-typescript-node-package/blob/0307eba66fe59c3a89a189352fd4797aad37736f/src/bin/index.ts#L34-L40

I think you'll want to add a `--version` arg there with a `-v` shorthand. See https://nodejs.org/api/util.html#utilparseargsconfig for examples of `short`.

### PR DESCRIPTION
**Pull request by xl4624**
## PR Checklist

- [x] Addresses an existing open issue: fixes #704
- [x] That issue was marked as [`status: accepting prs`](https://github.com/JoshuaKGoldberg/create-typescript-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22status%3A+accepting+prs%22)
- [x] Steps in [CONTRIBUTING.md](https://github.com/JoshuaKGoldberg/create-typescript-app/blob/main/.github/CONTRIBUTING.md) were taken

## Overview

I was browsing the list of issues labeled `good first issue` and saw that issue #704 had its attached PR closed. The version feature has basically already been implemented, but this just adds the flag to display the version.

🧢

### CODE REVIEW

**Review by JoshuaKGoldberg — CHANGES_REQUESTED** [review]
Looks like you're making good progress - and thanks for adding a test too! 🙌

Let me know if you need any help fixing up the last bits of complaints. https://github.com/JoshuaKGoldberg/create-typescript-app/blob/386bd14573d1ea1230e9adbe8436e935d7077c27/.github/DEVELOPMENT.md#development describes the things that are failing so far, and has a link at the top to a blog post too.

**Comment by xl4624** [comment]
Yeah I think I fixed it? The issue was that my PR wasn't updated to the changes from the upstream repository, right? I kind of messed up and had to `git push --force`

From the blog:
```
git checkout main
git pull upstream main
git push
```
Once I do this step to update my local/origin main, do I need to `git checkout feature-branch` and then `git merge main` to apply these changes to my feature branch?

**Comment by JoshuaKGoldberg** [comment]
> Once I do this step to update my local/origin main, do I need to `git checkout feature-branch` and then `git merge main` to apply these changes to my feature branch?

Yup, exactly! Now that your `main` is in sync with the upstream's, those are the two commands that will merge in the commits from `main` to your feature branch.

Though, I think the lint errors are legit and not from some history weirdness. From the [linked ❌ lint report](https://github.com/JoshuaKGoldberg/create-typescript-app/actions/runs/7052968781/job/19235527071?pr=1063):

```plaintext
/home/runner/work/create-typescript-app/create-typescript-app/src/bin/index.test.ts
Error:   6:1  error  Expected "./index.js" to come before "./packageJson.js"  perfectionist/sort-imports
```

The ESLint extension for your editor should be able to auto-fix that. Alternately, `pnpm run lint --fix` should do it for you.

**Review by JoshuaKGoldberg — APPROVED** [review]
💯, perfect - thanks for this!

**Comment by JoshuaKGoldberg** [comment]
@all-contributors please add @xl4624 for code.

> 🤖 Beep boop! This comment was added automatically by [all-contributors-auto-action](https://github.com/marketplace/actions/all-contributors-auto-action).
> Not all contributions can be detected from Git & GitHub alone. Please comment any missing contribution types this bot missed.
> ...and of course, thank you for contributing! 💙

**Pull request merged**
