### PR TITLE
chore: add updated test for createWithOptions.ts 

### LINKED ISSUE #874: 🧪 Testing: Fill in unit test coverage for createWithOptions.ts
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/create-typescript-app/issues?q=is%3Aissue) and found none that matched my issue.

### Overview

Splitting out of #869: the `createWithOptions` function is not currently unit tested. I'd love to see some unit tests added for it!

https://app.codecov.io/gh/JoshuaKGoldberg/create-typescript-app/blob/094b253411168038a2c7585e5172f8b773c18ea2/src%2Fcreate%2FcreateWithOptions.ts

### Additional Info

It'll be a little verbose to set up, but a unit test file should be able to [Vitest mock](https://vitest.dev/guide/mocking.html) out all the functions being called (`writeStructure`, `writeReadme`, etc.). And it'll likely have to mock out `withSpinners`, too, to directly call each of the functions provided in order.

### PR DESCRIPTION
**Pull request by kristo-baricevic**
## PR Checklist

- [x] Addresses an existing open issue: fixes #874 
- [x] That issue was marked as [`status: accepting prs`](https://github.com/JoshuaKGoldberg/create-typescript-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22status%3A+accepting+prs%22)
- [x] Steps in [CONTRIBUTING.md](https://github.com/JoshuaKGoldberg/create-typescript-app/blob/main/.github/CONTRIBUTING.md) were taken

## Overview

This is a test file for createWithOptions. It tests the logic of createWithOptions.. 

This PR is an extension of a previous PR, #1119.

### CODE REVIEW

**Comment by kristo-baricevic** [comment]
I'm happy to make any additional changes, let me know if I missed anything. Thanks!

**Review by JoshuaKGoldberg — APPROVED** [review]
💯, this is great - thanks @kristo-baricevic!  

Muppet-style puppet happily dancing around in confetti on an orange background

**Comment by JoshuaKGoldberg** [comment]
Btw, this wouldn't be a `feat:` as it's not user-facing. It'd be a `chore:` or `test:`. https://www.conventionalcommits.org

**Comment by kristo-baricevic** [comment]
Oh thanks for fixing the name! And thanks for the help tidying this test up! I am stoked to contribute.

**Comment by JoshuaKGoldberg** [comment]
Excited to see the coverage jump up >=1% 😄

Screenshot of the README.md badges showing coverage at 95%

If you're interested, I bet #872 and #873 would be pretty similar PRs.

**Pull request merged**
